const crypto = require('crypto');

/**
 * Generates a crash point using HMAC-SHA256
 * @param {string} serverSeed - Hex string generated by server
 * @param {string} clientSeed - Hex string (can be changed by players/admin)
 * @returns {number} Crash point
 */
function generateCrashPoint(serverSeed, clientSeed) {
  const hash = crypto
    .createHmac('sha256', serverSeed)
    .update(clientSeed)
    .digest('hex');

  // Use the first 8 characters (32 bits) of the hash
  const hex = hash.substring(0, 8);
  const intVal = parseInt(hex, 16);

  // 1 in 33 rounds (approx 3%) will result in an instant 1.00x crash
  if (intVal % 33 === 0) return 1.00;

  // Multiplier formula: (2^32 - hash_val) / (2^32 - hash_val) is simplified
  // Standard logic: multiplier = 99 / (100 - random_percentage)
  // We use the hash to determine the percentage
  const h = intVal;
  const e = Math.pow(2, 32);
  const multiplier = Math.floor((100 * e - h) / (e - h)) / 100;
  
  return Math.max(1.00, multiplier);
}

module.exports = { generateCrashPoint };
